
server:
  port: 8081

spring:
  application:
    name: 'fornecedor'
  datasource:
    url: "jdbc:mysql://localhost:3306/fornecedor"
    username: root
    password: admserver
  jpa:
    hibernate:
      ddl-auto: update
    
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka